### ISSUE TITLE
Falsche Definition von least_upper_bound_property (in REALS.ftl)?

### ISSUE THREAD

**Issue by DMeyer2** [RGiga4/FTL-Set#1]
Laut der Definition müsste auch die leere Menge ein reelles Supremum haben, was falsch ist. Meiner Meinung nach müsste Zeile 140 zu "R is lub iff for every subset A of R such that A is not empty..." geändert werden um das zu fixen.

**Comment by RGiga4** [comment]
Ist in Reals_A und Reals_B, Ord_set jetzt drin und in Master in lub drin
